apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: node-echo-service
  labels:
    app: node-echo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-echo-service
  template:
    metadata:
      labels:
        app: node-echo-service
    spec:
      containers:
      - name: node-echo-service
        image: diversario/node-echo-service:1.0.0
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: node-echo-service
spec:
  selector:
    app: node-echo-service
  ports:
  - protocol: TCP
    name: echo
    port: 2000
    targetPort: 3000
  - protocol: TCP
    name: extra
    port: 3000
    targetPort: 4000
  - protocol: TCP
    name: file
    port: 4000
    targetPort: 5000
